### ISSUE TITLE
mrs_two_ui和mrs_two的区别

### ISSUE THREAD

**Issue by shiningliang** [bamtercelboo/cnn-lstm-bilstm-deepcnn-clstm-in-pytorch#1]
我看到text_field和static_text_field在build_vocab时有差异，请问是前者只针对训练数据构建vocab，后者针对所有数据构建vocab吗？

**Comment by dalinvip** [comment]
你好，是这样的。




No matter where you are , even in despair, believe && smile.
在2018年6月10日 11:14，Liang Shining<notifications@github.com> 写道：

我看到text_field和static_text_field在build_vocab时有差异，请问是前者只针对训练数据构建vocab，后者针对所有数据构建vocab吗？
