### ISSUE TITLE
About the Accuracy and parameter setting

### ISSUE THREAD

**Issue by ghost** [bamtercelboo/cnn-lstm-bilstm-deepcnn-clstm-in-pytorch#2]
I tested your Bigru and Bilstm model with default setting, but I the accuracy is 81% and 79%.
It is much lower than the result you showed the in readme.
Can you show me the parameter setting? The unit num, layer num, optimizer?
Thank you!

**Comment by dalinvip** [comment]
Ok, I have upload log_bilstm and log_bigru in result, moreover, upload a word2vec file in word2vec, you can see log for detail.
