### ISSUE TITLE
`optim_momentum_value` for SDG in train_ALL_LSTM

### ISSUE THREAD

**Issue by wayne-ss** [bamtercelboo/cnn-lstm-bilstm-deepcnn-clstm-in-pytorch#3]
https://github.com/bamtercelboo/cnn-lstm-bilstm-deepcnn-clstm-in-pytorch/blob/1efb2be7868432f0264ad1124a4b9c0c959286f2/train_ALL_LSTM.py#L30-L33

I guess the `momentum=args.momentum_value` should be `momentum=args.optim_momentum_value`, as it is defined in:

https://github.com/bamtercelboo/cnn-lstm-bilstm-deepcnn-clstm-in-pytorch/blob/1efb2be7868432f0264ad1124a4b9c0c959286f2/Config/config.py#L279-L281

---
I would like to contribute/fix small changes like above in your repo? Is there a way I can help with (like pull requests, or slack group)?

**Comment by dalinvip** [comment]
thanks, I have fixed it
