### ISSUE TITLE
运行到for batch in train_iter的时候报错了，RuntimeError: sizes must be non-negative

### ISSUE THREAD

**Issue by Kryptonites** [bamtercelboo/cnn-lstm-bilstm-deepcnn-clstm-in-pytorch#5]
我把2分类改成了多分类
examples += [data.Example.fromlist([sentence, flag], fields=fields)]
flag对应line[-2]的值

**Comment by dalinvip** [comment]
reference https://github.com/bamtercelboo/cnn-lstm-bilstm-deepcnn-clstm-in-pytorch/blob/master/DataLoader/mydatasets_self_five.py
