### ISSUE TITLE
model_CNN.py中self.fc1,和self.fc2没有定义

### ISSUE THREAD

**Issue by redinton** [bamtercelboo/cnn-lstm-bilstm-deepcnn-clstm-in-pytorch#6]
model/model_CNN.py中115,116行中的self.fc1,和self.fc2没有定义，另外想请教一下为什么用了BN就要再多定义一个隐层？

**Comment by dalinvip** [comment]
ok，默认batch_norm是False，疏忽了这个定义，thanks.
