### ISSUE TITLE
学习

### ISSUE THREAD

**Issue by iiiiwanttoknow** [bamtercelboo/cnn-lstm-bilstm-deepcnn-clstm-in-pytorch#7]
大佬您好，您的代码非常有启发性，但是我在调试学习的过程中发现主函数main.py中有一些如config.static_text_field的文件并没有在config文件中出现并指向任何文件，请问您是否方便添加一下示例文件以供学习呢？

**Comment by dalinvip** [comment]
您好，可以直接看代码的(https://github.com/bamtercelboo/cnn-lstm-bilstm-deepcnn-clstm-in-pytorch/blob/master/main.py#L211)，代码已经写完有很长的一段时间了，易读性上面可能还有待完善，感谢。

**Comment by iiiiwanttoknow** [comment]
您好，感谢您的回复，但是对代码里提到的config.static_text_field等一些配置，不知是否是我有所遗漏，在您提供的代码里并没有体现,，所以您的代码很遗憾我没办法成功运行！最后希望如果可能的话可以更新一下代码，您的代码将会成为一份特别棒的参考！

**Comment by dalinvip** [comment]
您好，代码是没有问题，我刚才测试了代码，特别测试了和static_text相关的CNN_MUI和Deep_CNN_MUI。
代码跑不起来的原因：请确保你的运行环境和README一致，另外，详细阅读READNE。
代码现在已经是PyTorch1.0版本，已经属于PyTorch稳定版本，而且，由于最近时间很紧，近期不会更新， 谢谢。
